export { ReactComponent as CheckBoxIcon } from './checkBox.svg'
export { ReactComponent as CheckBoxOutlineIcon } from './checkBoxOutline.svg'
export { ReactComponent as CircleIcon } from './circle.svg'
export { ReactComponent as FullCircleIcon } from './fullCircle.svg'
export { ReactComponent as ParagraphIcon } from './paragraph.svg'
export { ReactComponent as ShortTextIcon } from './shortText.svg'
export { ReactComponent as DropdownIcon } from './dropdown.svg'
export { ReactComponent as XIcon } from './x.svg'
